name: MyCounter.IO Action
description: Read counter value from MyCounter.IO service and set it as output.
author: Platform Online LLC

branding:
  icon: hash
  color: gray-dark

inputs:
  apikey:
    description: 'API Key for MyCounter.IO service'
    required: true
    default: ''
  workspace:
    description: 'Workspace alias name in MyCounter.IO'
    required: true
    default: ''
  counter:
    description: 'Counter alias name in MyCounter.IO'
    required: true
    default: ''
  action:
    description: 'Action to perform: get, increment, decrement, set'
    required: true
    default: ''
  value:
    description: 'Value to set when action is set'
    required: false
    default: '1'
  
outputs:
  status:
    description: The status of the action performed
  action:
    description: The action performed
  value:
    description: The counter value after performing the action

runs:
  using: node24
  main: dist/index.js
